name: config_theme
description: "this module make you can config theme easily"
#publish_to: 'none'
#repository: https://github.com/juneflow-songdo/config_theme

version: 0.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  june_flow_util: ^0.8.19

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/config_theme/
  uses-material-design: true